project_id = "sdberrkfwoozezletfuq"

[functions.delete-user]
verify_jwt = true

[functions.generate-recurring-transactions]
verify_jwt = false

[functions.generate-fixed-transactions-yearly]
verify_jwt = false

[functions.atomic-transaction]
verify_jwt = true

[functions.atomic-transfer]
verify_jwt = true

[functions.atomic-edit-transaction]
verify_jwt = true

[functions.atomic-delete-transaction]
verify_jwt = true

[functions.atomic-transaction]
verify_jwt = true

[functions.atomic-transfer]
verify_jwt = true

[functions.atomic-edit-transaction]
verify_jwt = true

[functions.atomic-delete-transaction]
verify_jwt = true