project_id = "sdberrkfwoozezletfuq"

[functions.delete-user]
verify_jwt = true

[functions.generate-recurring-transactions]
verify_jwt = false

[functions.generate-fixed-transactions-yearly]
verify_jwt = false